2022-1-CECD3-2yi2ji-4/mainSite/kiosk/urls.py
from django.urls import path

from . import views

app_name = "kiosk" # 앱 이름 설정
urlpatterns = [
    path('', views.index, name='index'),
    path('upload', views.upload, name='upload'),
]

2022-1-CECD3-2yi2ji-4/mainSite/mainSite/urls.py
from django.contrib import admin
from django.urls import path, include
#from ocr import views, urls
from .views import *
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name="main"),
    path('kiosk/', include('kiosk.urls')),
    path('object/', include('objectRecog.urls')),
    path('setting/', include('setting.urls')),
    path('tesseract/', include('tesseractocr.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

2022-1-CECD3-2yi2ji-4/mainSite/objectRecog/urls.py
from django.urls import path

from . import views
from django.conf import settings 
from django.conf.urls.static import static

app_name = "object"
urlpatterns = [
  path('', views.barcode, name='barcode'),
  path('send/', views.send, name="send"),
  # path('', views.objectIndex, name='objectIndex'),
  path('kakaoApi/', views.kakaoApi, name="kakaoApi"),
  path('sttFileApi/', views.sttFileApi, name="sttFileApi"),
  path('sttMicApi/', views.sttMicApi, name="sttMicApi"),
  path('ttsApi/', views.ttsApi, name="ttsApi"),
  path('roi/', views.roi, name="roi"),
  path('roiResult/', views.roiResult, name="roiResult"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

2022-1-CECD3-2yi2ji-4/mainSite/mainSite/views.py
from django.shortcuts import render

def main(request):
  return render(request, 'main.html')

2022-1-CECD3-2yi2ji-4/mainSite/mainSite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>kiosk</title>
  </head>
  <body>
    base.html <br />
    {% block content %} {% endblock %}
  </body>
</html>

2022-1-CECD3-2yi2ji-4/mainSite/mainSite/templates/main.html
{% extends 'base.html' %}
<!--  -->
{% load static %}
<!--  -->
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />

<a id="btn1" href="{% url 'kiosk:index' %}">카메라</a>
<a id="btn2" href="{% url 'object:barcode' %}">물체인식</a>

<!-- <img src="{% static 'images/image.png' %}" alt="웨않되" /> -->

{% endblock %}