2022-1-CECD3-2yi2ji-4/mainSite/kiosk/urls.py
from django.urls import path

from . import views

app_name = "kiosk" # 앱 이름 설정
urlpatterns = [
    path('', views.index, name='index'),
    path('upload', views.upload, name='upload'),
]

2022-1-CECD3-2yi2ji-4/mainSite/mainSite/urls.py
from django.contrib import admin
from django.urls import path, include
#from ocr import views, urls
from .views import *
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name="main"),
    path('kiosk/', include('kiosk.urls')),
    path('object/', include('objectRecog.urls')),
    path('setting/', include('setting.urls')),
    path('tesseract/', include('tesseractocr.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

2022-1-CECD3-2yi2ji-4/mainSite/kiosk/models.py
from django.db import models

# Create your models here.

2022-1-CECD3-2yi2ji-4/mainSite/kiosk/views.py
from django.http import HttpResponse

# Create your views here.
from django.shortcuts import render
from django.conf import settings
import base64

def index(request):
    return render(request, 'kioskMain.html')

def upload(request):
  data = request.POST.__getitem__('data')
  data = data[22:]
  path = str(settings.MEDIA_ROOT)
  filename = 'image1.png'
  image = open(path+'/'+filename, "wb")
  image.write(base64.b64decode(data))
  image.close()
  # answer = {'filename' : filename}
  return render(request, 'kioskMain.html')

2022-1-CECD3-2yi2ji-4/mainSite/kiosk/templates/kioskMain.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta
      http-equiv="Content-Security-Policy"
      content="upgrade-insecure-requests"
    />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Camera Web App</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/kiosk.css' %}"
    />
  </head>
  <body>
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <div id="header">
      <h3>Simple Web Camera</h3>
      <p>버튼을 클릭 하세요.</p>
      <button id="camera--trigger">사진촬영</button>
    </div>
    <main id="camera">
      <canvas id="camera--sensor"></canvas>

      <!-- 비디오 -->
      <video id="camera--view" autoplay playsinline></video>

      <!-- 캡쳐사진 -->
      <img src="//:0" alt="" id="camera--output" />
      <!-- <img src="" id="media_file" /> -->
    </main>

    <script>
      let constraints = { video: { facingMode: "environment" }, audio: false };
      const cameraView = document.querySelector("#camera--view");
      const cameraOutput = document.querySelector("#camera--output");
      const cameraSensor = document.querySelector("#camera--sensor");
      const cameraTrigger = document.querySelector("#camera--trigger");
      // const cameraMedia = document.querySelector("#media_file");

      function cameraStart() {
        navigator.mediaDevices
          .getUserMedia(constraints)
          .then(function (stream) {
            track = stream.getTracks()[0];
            cameraView.srcObject = stream;
          })
          .catch(function (error) {
            console.error("카메라에 문제가 있습니다.", error);
          });
      }

      //촬영 버튼 클릭 리스너
      cameraTrigger.addEventListener("click", function () {
        cameraSensor.width = cameraView.videoWidth; //640으로 정해져서 나오네?
        cameraSensor.height = cameraView.videoHeight;
        cameraSensor.getContext("2d").drawImage(cameraView, 0, 0);
        cameraOutput.src = cameraSensor.toDataURL("image/png");
        // cameraMedia.src = "{% static 'mainSite/media/image.png' %} ";
        cameraOutput.classList.add("taken");

        $.ajax({
          type: "POST",
          url: "{% url 'kiosk:upload' %}",
          headers: {
            "X-CSRFTOKEN": "{{ csrf_token }}",
          },
          data: { data: cameraOutput.src },
          success: function (result) {
            console.log("success");
          },
          error: function (e) {
            console.log("error");
            console.log(e);
          },
        });
      });

      // 페이지가 로드되면 함수 실행
      window.addEventListener("load", cameraStart, false);
    </script>
  </body>
</html>